### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '.'

### ISSUE THREAD

**Issue by lauscherin** [thlee/SNPhylo#7]
Hi,

I tried to use SNPhylo with a vcf-file and got the following error message:

  File "/snphylo/scripts/remove_low_depth_genotype_data.py", line 68, in <module>
    if int(genotype_col[dp_col_no]) < min_depth:
ValueError: invalid literal for int() with base 10: '.'

I think the problems lies within the vcf-file. What could I do?

Many thanks in advance,
Angela

**Comment by thlee** [comment]
Dear Dr. Angela Noll,

I modified the script, remove_low_depth_genotype_data.py, to print the line
leading the error.
Thus, could you replace the old script with the new one and send the output
in order to find the reason of the error?

Thank you,

Tae-Ho Lee

2015-11-16 19:19 GMT+09:00 Angela Noll <notifications@github.com>:

**Comment by akinyanju** [comment]
I am having similar issue here. I got an error like this even after i have downloaded another the entire snphylo new package. What should i do?

Start to remove low quality data.
Traceback (most recent call last):
  File "/home/plxral/Downloads/Phylogeny/Autosome/Chr24/full/snphylo/scripts/remove_low_depth_genotype_data.py", line 68, in <module>
    if int(genotype_col[dp_col_no]) < min_depth:
ValueError: invalid literal for int() with base 10: '.'

LAWAL

**Comment by lauscherin** [comment]
Hey,

I¹m sorry for the delayed answer but my computer was very busy the last
weeks
I started your script update but (I think) nothing changed in the output:

$ ./snphylo.sh -v gatk.filtered.vcf

Start to remove low quality data.

Traceback (most recent call last):

  File "remove_low_depth_genotype_data.py", line 68, in <module>

    if int(genotype_col[dp_col_no]) < min_depth:

ValueError: invalid literal for int() with base 10: '.'


May thanks in advance,
Angela

From:  Tae-Ho Lee <notifications@github.com>
Reply-To:  thlee/SNPhylo
<reply+00a9392f89be673053ff2981b8df04e6e7b7d1c4d622dcfa92cf000000011265a8e19
2a169ce06faac28@reply.github.com>
Date:  Thursday 19 November 2015 16:12
To:  thlee/SNPhylo <SNPhylo@noreply.github.com>
Cc:  Angela Noll <angienoll@gmx.de>
Subject:  Re: [SNPhylo] ValueError: invalid literal for int() with base 10:
'.' (#7)

Dear Dr. Angela Noll,

I modified the script, remove_low_depth_genotype_data.py, to print the line
leading the error.
Thus, could you replace the old script with the new one and send the output
in order to find the reason of the error?

Thank you,

Tae-Ho Lee

2015-11-16 19:19 GMT+09:00 Angela Noll <notifications@github.com>:

> Hi,
>
> I tried to use SNPhylo with a vcf-file and got the following error message:
>
> File "/snphylo/scripts/remove_low_depth_genotype_data.py", line 68, in
> if int(genotype_col[dp_col_no]) < min_depth:
> ValueError: invalid literal for int() with base 10: '.'
>
> I think the problems lies within the vcf-file. What could I do?
>
> Many thanks in advance,
> Angela
>
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/thlee/SNPhylo/issues/7>.
>


Reply to this email directly or view it on GitHub
<https://github.com/thlee/SNPhylo/issues/7#issuecomment-158085169> .

**Comment by akinyanju** [comment]
I got exactly the same error Angela got. My input.vcf file is a merged file which is what i expected the program require. Hopefully, this will be fix soonest

**Comment by akinyanju** [comment]
Hi Dr Lee,

Thank you for inventing the program snphylo. I am trying torun the program for my vcf file and I encountered the following error


 
Start to remove low quality data.

Traceback (most recent call last):

  File"/home/plxral/Downloads/Phylogeny/Autosome/Chr24/full/snphylo/scripts/remove_low_depth_genotype_data.py",line 68, in <module>

    if int(genotype_col[dp_col_no]) <min_depth:

ValueError: invalid literal for int() with base 10: '.'


 
This is my commad line

perl snphylo.sh -v/home/plxral/Downloads/Phylogeny/Autosome/Chr24/full/Gallus.vcf -l LD_threshold0.1 -m MAF_threshold 0.1 -M Missing_rate 0.1 -b -BThe_number_of_bootstrap_samples 1000 -a The_number_of_the_last_autosome 28 –A

 

LAWAL, Raman AkinyanjuPhD Genetics (Student) School of Life Sciences, University Park. University of Nottingham. NG7 2RD. UK.
+447778330433
Skype name: Lawal raman akinyanju 


    On Monday, November 30, 2015 5:12 PM, Angela Noll <notifications@github.com> wrote:
 

 Hey,

I¹m sorry for the delayed answer but my computer was very busy the last
weeks
I started your script update but (I think) nothing changed in the output:

$ ./snphylo.sh -v gatk.filtered.vcf

Start to remove low quality data.

Traceback (most recent call last):

 File "remove_low_depth_genotype_data.py", line 68, in <module>

 if int(genotype_col[dp_col_no]) < min_depth:

ValueError: invalid literal for int() with base 10: '.'


May thanks in advance,
Angela

From: Tae-Ho Lee <notifications@github.com>
Reply-To: thlee/SNPhylo
<reply+00a9392f89be673053ff2981b8df04e6e7b7d1c4d622dcfa92cf000000011265a8e19
2a169ce06faac28@reply.github.com>
Date: Thursday 19 November 2015 16:12
To: thlee/SNPhylo <SNPhylo@noreply.github.com>
Cc: Angela Noll <angienoll@gmx.de>
Subject: Re: [SNPhylo] ValueError: invalid literal for int() with base 10:
'.' (#7)

Dear Dr. Angela Noll,

I modified the script, remove_low_depth_genotype_data.py, to print the line
leading the error.
Thus, could you replace the old script with the new one and send the output
in order to find the reason of the error?

Thank you,

Tae-Ho Lee

2015-11-16 19:19 GMT+09:00 Angela Noll <notifications@github.com>:

> Hi,
>
> I tried to use SNPhylo with a vcf-file and got the following error message:
>
> File "/snphylo/scripts/remove_low_depth_genotype_data.py", line 68, in
> if int(genotype_col[dp_col_no]) < min_depth:
> ValueError: invalid literal for int() with base 10: '.'
>
> I think the problems lies within the vcf-file. What could I do?
>
> Many thanks in advance,
> Angela
>
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/thlee/SNPhylo/issues/7>.
>


Reply to this email directly or view it on GitHub
<https://github.com/thlee/SNPhylo/issues/7#issuecomment-158085169> .

**Comment by thlee** [comment]
I am pleased to announce that a new release of the **remove_low_depth_genotype_data.py** file.
The file was modified to prevent ValueError for a certain vcf file.
Please check the new file. Thank you for your waiting.

Sincerely,

Tae-Ho Le
